# Generated by Django 2.1.7 on 2019-12-24 16:20

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='Update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete sign')),
                ('name', models.CharField(max_length=20, verbose_name='Goods SPU Name')),
                ('detail', tinymce.models.HTMLField(blank=True, verbose_name='Goods Detail')),
            ],
            options={
                'verbose_name': 'Goods SPU',
                'verbose_name_plural': 'Goods SPU',
                'db_table': 'df_goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='Update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete sign')),
                ('image', models.ImageField(upload_to='goods', verbose_name='Image Path')),
            ],
            options={
                'verbose_name': 'Goods Image',
                'verbose_name_plural': 'Goods Image',
                'db_table': 'df_goods_image',
            },
        ),
        migrations.CreateModel(
            name='GoodsSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='Update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete sign')),
                ('name', models.CharField(max_length=20, verbose_name='Goods Name')),
                ('desc', models.CharField(max_length=256, verbose_name='Goods Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Goods Price')),
                ('unite', models.CharField(max_length=20, verbose_name='Goods Unite')),
                ('image', models.ImageField(upload_to='goods', verbose_name='Goods image')),
                ('stock', models.IntegerField(default=1, verbose_name='Goods Stock')),
                ('sales', models.IntegerField(default=0, verbose_name='Goods Sales')),
                ('status', models.SmallIntegerField(choices=[(0, 'out of stock'), (1, 'in stock')], default=1, verbose_name='Goods Status')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.Goods', verbose_name='Goods SPU')),
            ],
            options={
                'verbose_name': 'Goods',
                'verbose_name_plural': 'Goods',
                'db_table': 'df_goods_sku',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='Update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete sign')),
                ('name', models.CharField(max_length=20, verbose_name='Type name')),
                ('logo', models.CharField(max_length=20, verbose_name='logo')),
                ('image', models.ImageField(upload_to='type', verbose_name='Type image')),
            ],
            options={
                'verbose_name': 'Goods Type',
                'verbose_name_plural': 'Goods Type',
                'db_table': 'df_goods_type',
            },
        ),
        migrations.CreateModel(
            name='IndexGoodsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='Update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete sign')),
                ('image', models.ImageField(upload_to='banner', verbose_name='Image')),
                ('index', models.SmallIntegerField(default=0, verbose_name='Index')),
                ('sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.GoodsSKU', verbose_name='Goods')),
            ],
            options={
                'verbose_name': 'Index Carousel Goods',
                'verbose_name_plural': 'Index Carousel Goods',
                'db_table': 'df_index_banner',
            },
        ),
        migrations.CreateModel(
            name='IndexPromotionBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='Update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete sign')),
                ('name', models.CharField(max_length=20, verbose_name='Promotion Name')),
                ('url', models.URLField(verbose_name='Promotion Link')),
                ('image', models.ImageField(upload_to='banner', verbose_name='Promotion Image')),
                ('index', models.SmallIntegerField(default=0, verbose_name='Index')),
            ],
            options={
                'verbose_name': 'Index Promotion',
                'verbose_name_plural': 'Index Promotion',
                'db_table': 'df_index_promotion',
            },
        ),
        migrations.CreateModel(
            name='IndexTypeGoodsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='Update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete sign')),
                ('display_type', models.SmallIntegerField(choices=[(0, 'Title'), (1, 'Image')], default=1, verbose_name='Display Type')),
                ('index', models.SmallIntegerField(default=0, verbose_name='Index')),
                ('sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.GoodsSKU', verbose_name='Goods SKU')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.GoodsType', verbose_name='Goods Type')),
            ],
            options={
                'verbose_name': 'Index Type Goods',
                'verbose_name_plural': 'Index Type Goods',
                'db_table': 'df_index_type_goods',
            },
        ),
        migrations.AddField(
            model_name='goodssku',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.GoodsType', verbose_name='Goods Type'),
        ),
        migrations.AddField(
            model_name='goodsimage',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.GoodsSKU', verbose_name='Goods'),
        ),
    ]
