# Generated by Django 2.1.7 on 2019-12-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='Update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete sign')),
                ('count', models.IntegerField(default=1, verbose_name='Goods Count')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gods Price')),
                ('comment', models.CharField(default='', max_length=256, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Order Goods',
                'verbose_name_plural': 'Order Goods',
                'db_table': 'df_order_goods',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='Update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete sign')),
                ('order_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Order id')),
                ('pay_method', models.SmallIntegerField(choices=[(1, 'Cash on delivery'), (2, 'Mastercard'), (3, 'Visa'), (4, 'AmericanExpress')], default=3, verbose_name='Pay Method')),
                ('total_count', models.IntegerField(default=1, verbose_name='Goods Count')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Goods Price')),
                ('transit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Delivery Price')),
                ('order_status', models.SmallIntegerField(choices=[(1, 'UNPAID'), (2, 'UNSEND'), (3, 'UNRECEIVED'), (4, 'UNCOMMENT'), (5, 'FINISHED')], default=1, verbose_name='Order Status')),
                ('trade_no', models.CharField(default='', max_length=128, verbose_name='Trade Number')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
                'db_table': 'df_order_info',
            },
        ),
    ]
